travis:
  secure:
    BINSTAR_TOKEN: xXMtHYFTv2SMTjhC+mEsJqvgV2Cb+L/Jfu4/0jVACfOaf6YXz15fFTRrCpoaWam6mS6Lib/W+UAcFtTBYXmPsMpEsdGOwtgVpHeCsGyLH3WO3xd/v10rzI2Lb1/ZoiMvMuRQMaXS6aB82FsBNIB3kkNRU6wI0s0zcS529OXAa2JbIx64kkKZttQsekU/lVmIB2voYpBRg+ZNuTEiCyA2fBiKo60l/HK1kN5mp8La84w0Vkc40DTW4CeP9APbasMZqgelliyyaSlGNwnmrd/TxZ5YdLWAWFf/K9t3q4FO5g34xf6DHAMFTtu05Ey1UahHmAagWncHyhiqXKrszLxbwHBI+Rit2OWtZeIjWt5GyJKTjwtdiry5NxGQM9kg6q6wpCCPgS9Q+A9NbS+px6Jwgb58Pnrt5uU3jBekt4r36FZyR140WKQkOSoZFOlfr75HHoejtl1FnG9z2wpu3jxqaRJffcx/OZOYbDZf4T7uNNByLzjRBx7JOSb9UiW3ELYoGw5iPDu9zJjrBvIh3xtdTWzoxt/MjevPMz+Mtbh5RhGrCKDWJUdHAiAYNag7Woh+NcelWo57Ivjh8S6amGyDOGqvQSDy72ok7iZUNKPpeKna91+4P6mN6GLjMLz3B5qHayU8GmFZHrootiTFYpRLqJ+MNCxql1HKal+iJJEH0bw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
